### ISSUE TITLE
Two issues with qbsolv 0.2.3

### ISSUE THREAD

**Issue by sploiber** [dwavesystems/qbsolv#108]
Two issues:

One:

Installation was failing; 
and an error message was printing about some clashing of versions:

I have a problem with the new code:
 
mport numpy as np
from dwave_sapi_dimod import SAPISampler
from dwave_sapi_dimod import EmbeddingComposite
from dwave_qbsolv import QBSolv
 
Traceback (most recent call last):
  File "customer.py", line 2, in <module>
    from dwave_sapi_dimod import SAPISampler
  File "//anaconda/lib/python2.7/site-packages/dwave_sapi_dimod/__init__.py", line 9, in <module>
    from dwave_sapi_dimod.samplers import *
  File "//anaconda/lib/python2.7/site-packages/dwave_sapi_dimod/samplers.py", line 26, in <module>
    class SAPILocalSampler(dimod.TemplateSampler):
AttributeError: 'module' object has no attribute 'TemplateSampler'
 
Two:

Exception TypeError: TypeError("expected 'num_occurences' to be a positive int",) in 'dwave_qbsolv.qbsolv_binding.solver_callback' ignored​

On this second one, the code didn't throw this message when running on a local machine, but when the code was running on the D-Wave QPU, this message was thrown. The runs would proceed; but this message was generated.

**Comment by bellert** [comment]
Closed by #107
