### ISSUE TITLE
memory request error

### ISSUE THREAD

**Issue by yongchengding** [dwavesystems/qbsolv#140]
I got a huge QUBO matrix with the size of 872760*872760 to be solved by qbsolv and it says

 qbsolv error - memory request for X[872760][872760], -834 Mbytes  denied

I'm wondering if there is any solution to this, is 16GB memory enough for solving this problem? Or I should just use a cluster with more memory to solve it?

small qubo matrix with the size of 140*140 is ok, on both local tabu solver and D-Wave sampler. Thanks in advance.

**Comment by arcondello** [comment]
Hi @yongchengding , a qubo matrix of that size (with single precision floats) would need `872760*872760*4` bytes, or ~3 TB of memory.

**Comment by mwbooth** [comment]
Alex is correct expect qbsolv uses double precision floats. So that would be 6tb

Regards

Mike
Mike Booth
Mie@hpcresults.com

**Comment by yongchengding** [comment]
> Hi @yongchengding , a qubo matrix of that size (with single precision floats) would need `872760*872760*4/2` bytes, or ~1.5 TB of memory.
> 
> It is probable that your problem could be expressed with a smaller formulation. Is there anything you can tell us about how you're generating the matrix?

Thanks a lot. I've reduced the problem to a smaller scale and the result was perfect!

**Comment by arcondello** [comment]
Great!
