### ISSUE TITLE
AttributeError: 'Response' object has no attribute 'data_vectors'

### ISSUE THREAD

**Issue by pererahasitha** [dwavesystems/qbsolv#141]
**Description**
Try to execute Example in https://docs.ocean.dwavesys.com/projects/qbsolv/en/latest/intro.html page 
and got following AttributeError.

AttributeError: 'Response' object has no attribute 'data_vectors'

**To Reproduce**
Execution sequence as follows
C:\>python
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from dwave_qbsolv import QBSolv
>>> import neal
>>> import itertools
>>> import random
>>> qubo_size = 500
>>> subqubo_size = 30
>>> Q = {t: random.uniform(-1, 1) for t in itertools.product(range(qubo_size), repeat=2)}
>>> sampler = neal.SimulatedAnnealingSampler()
>>> response = QBSolv().sample_qubo(Q, solver=sampler, solver_limit=subqubo_size)
>>> print("energies=" + str(list(response.data_vectors['energy'])))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Response' object has no attribute 'data_vectors'
>>>

**Environment:**

my qbsolv version as follows
>pip show dwave-qbsolv
Name: dwave-qbsolv
Version: 0.2.10
Summary: UNKNOWN
Home-page: UNKNOWN
Author: None
Author-email: None
License: Apache 2.0
Location: c:\programdata\anaconda3\lib\site-packages
Requires: dimod
Required-by: dwave-ocean-sdk

I run this example in my Windows 10 environment.

seems that Version: 0.2.10 is deffer with the https://docs.ocean.dwavesys.com/projects/qbsolv/en/latest/intro.html documentation.
How should i find correct document for the Version: 0.2.10?
or is it the bug of Version: 0.2.10?

**Comment by arcondello** [comment]
Hi @pererahasitha , I believe this should be fixed by the latest release of dimod https://github.com/dwavesystems/dimod/releases/tag/0.8.6.

See also:
https://github.com/dwavesystems/dimod/issues/393
https://github.com/dwavesystems/dimod/pull/415

Try running `pip install dimod --upgrade` and let us know if it resolves the problem
