### ISSUE TITLE
Is is possible to run qbsolv in Jupyter notebook?

### ISSUE THREAD

**Issue by kcLin2708** [dwavesystems/qbsolv#154]
**Description**
Can't run qbsolv in Jupyter notebook. I must write code in a python file to run qbsolv

**Expected behavior**
Is it possible to make the execution of qbsolv in Jupyter notebook file.

**Environment:**
 - OS: Ubuntu 18.04.4 
 - Python version: 3.7

**Comment by randomir** [comment]
It is possible. I've just verified in our [JHub](https://cloud.dwavesys.com/leap/learning/):
![image](https://user-images.githubusercontent.com/447371/118272749-ec177400-b477-11eb-8d31-8dc91ef6804d.png)

Can you post the error message you're seeing?

**Comment by kcLin2708** [comment]
@randomir,

Thank you. I try to run qbsolv in Jupyter notebook and it works now (s. the following image).
![image](https://user-images.githubusercontent.com/22289840/118278611-77b9f080-b4ca-11eb-8caa-c2e018033d17.png)

I think the error was due to the installation because the pip install command didn't work for me. I've installed qbsolve via cloning the source code from github.

**Comment by randomir** [comment]
Thanks. I'll close this issue then.
