### ISSUE TITLE
Intermittently observing invalid output from QBSolv().sample_qubo. 

### ISSUE THREAD

**Issue by AjayKumar-LVLS** [dwavesystems/qbsolv#166]
**Description**
The output given by the QBSolv().sample_qubo are valid at one execution and is invalid at consecutive execution and vice versa. Invalid output - "the solver is not obeying the constraints that are added to the objective function".

I am executing a Mixed integer linear programming problem with constraints that is converted into a QUBO problem. 

Any help here is appreciated.

**Comment by arcondello** [comment]
Hi @AjayKumar-LVLS,

Can you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by mwbooth** [comment]
The solver is not deterministic.  You might see if running with a larger numrepeats solves your problem

**Comment by AjayKumar-LVLS** [comment]
> 

Hi mwbooth, 

I tried execution with large num_repeats, the results still give intermittently invalid outputs.

**Comment by mwbooth** [comment]
try a num_repeats of 50000

**Comment by mwbooth** [comment]
My belief is that what you are calling invalid outputs are really where qbsolv didn't find a low enough energy level to meet the constraint requirements.   Generally the qubo is encoded with constraints beint met at a higher energy level than the optimization values.

**Comment by AjayKumar-LVLS** [comment]
I did try with very large num repeats value and the solver is providing the solution that satisfies the constraints. however the execution time is increased exponentially. I would like to hear if there is any thing like dividing the problems and solving it, to make it faster with the Tabu solver or d-wave simulated annealing.
Thanks @mwbooth and @arcondello for your responses to the issues.
