### ISSUE TITLE
fatal error in directory "tests"

### ISSUE THREAD

**Issue by jmsellier** [dwavesystems/qbsolv#25]
Hello,

I downloaded the latest version of the code (updated in the weekend) and when trying to compile from the directory "tests" I got the following error:

cd ../src && make util.o
make[1]: Entering directory '/home/sellier/qbsolv-master/src'
make[1]: 'util.o' is up to date.
make[1]: Leaving directory '/home/sellier/qbsolv-master/src'
cd ../src && make solver.o
make[1]: Entering directory '/home/sellier/qbsolv-master/src'
make[1]: 'solver.o' is up to date.
make[1]: Leaving directory '/home/sellier/qbsolv-master/src'
cd ../src && make dwsolv.o
make[1]: Entering directory '/home/sellier/qbsolv-master/src'
make[1]: 'dwsolv.o' is up to date.
make[1]: Leaving directory '/home/sellier/qbsolv-master/src'
g++ solver_reduce.cpp ../src/util.o ../src/solver.o ../src/dwsolv.o -o solver_reduce -g -lgtest
solver_reduce.cpp:1:25: fatal error: gtest/gtest.h: No such file or directory
compilation terminated.
make: *** [Makefile:10: solver_reduce] Error 1

This used to work a few days ago. Did somebody change something?

I hope this helps,

JM Sellier

**Comment by adam-douglass** [comment]
This should be due to the dependency on the [googletest](https://github.com/google/googletest) framework being added. (you noted the failure to document that in another issue)

Would you mind trying again with that library installed?

**Comment by jmsellier** [comment]
It was due to googletest indeed. I installed it on a GNU/Linux system and compiled the files in the "tests" directory, it worked (I had to modify the Makefile though).

Thanks for the hint!

**Comment by adam-douglass** [comment]
Where they only modifications for your local path to the library? If it was something else I'd love to know.

**Comment by jmsellier** [comment]
Yes, it was the local path only. BTW it would be nice to include all these
details in the readme file. What do you think?

On Jan 18, 2017 8:41 PM, "Adam" <notifications@github.com> wrote:

Where they only modifications for your local path to the library? If it was
something else I'd love to know.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dwavesystems/qbsolv/issues/25#issuecomment-273579115>,
or mute the thread

**Comment by adam-douglass** [comment]
The dependency on gtest has been noted, so I'm going to close this based on that, but additions to the readme are, of course, welcome.
