### ISSUE TITLE
Feature request:  a command line option to avoid the trivial all zero solution

### ISSUE THREAD

**Issue by sabladmin1** [dwavesystems/qbsolv#29]
Since qbsolv is performing a minimisation of x'Qx, a trivial solution is one with all elements of x=0 .

Is it feasible for there to be a command-line option that forces the algorithm to avoid this trivial solution?

One way I suggest  is to add a large penalty term to the objective function, eg for a 4 element x vector, add the term K*(1-x1)*(1-x2)*(1-x3)*(1-x4) to the objective function, and default K to 0 (the user overrides this from the command line to set K).  I don't know whether this maps to the way D-wave hardware works though.

**Comment by adam-douglass** [comment]
This is actually a small misunderstanding of the objective function; if Q has negative values then we can't a priori know that zero is going to be a minimal value. 

Take an objective like:
<pre>
1 -3
0  1
</pre>
We can see that x will actually minimize the function as [1 1], with the energy `-1 = 1 * 1 + 1 * 1 + 1 * 1 * -3`. I hope this helps.

**Comment by sabladmin1** [comment]
Yes I see.
But look at a problem such as finding the lowest cost item out of a selection of 3: 

minimise x1*cost(item1) + x2*cost(item2) + x3*cost(item3)

Indeed 0 is a solution but it would not really be very interesting...
