### ISSUE TITLE
Is result of mapColoringUSStates correct by now?

### ISSUE THREAD

**Issue by tiancheng2000** [dwavesystems/qbsolv#41]
I've tried the classic *MapColoring* sample but got a seemingly incorrect [output SVG](https://github.com/dwavesystems/qbsolv/files/833161/usa.qbout.xaa.svg.txt).

**Environment**: Cygwin64_2.873, GNU make 4.2.1, Python 2.7.9.
**Intermediate Files**: [usa.qubo](https://github.com/dwavesystems/qbsolv/files/833175/usa.qubo.txt), [usa.qbout(i.e. "xaa")](https://github.com/dwavesystems/qbsolv/files/833174/usa.qbout.txt)

Does it means, currently *qbsolv* is still in its *simulated annealing* version, so cannot solve a N=51 NPC problem?

**Comment by mwbooth** [comment]
I have found the problem.  The .adj file has HI ( Hawaii ) listed incorrectly.  It should be after GA (Georgia)  The order of the states in usa.adj must correspond with the order of the states in blank_US_state_map.svg.  I will push a fix.

**Comment by mwbooth** [comment]
pushed a fix for example program   
The adj input was out of alignment with the blank map, also forced HI and AK to different colors in adj file, and one line of output was missing in the color_states.py program

**Comment by spreinhardt** [comment]
Excellent; thanks.                    Steve
