### ISSUE TITLE
Qbsolv and dwave_neal are not installing?

### ISSUE THREAD

**Issue by Frrank1** [dwavesystems/qbsolv#99]
Recently I upgraded my local servers of windows and linux. 
The problem is non of D-wave tools are installing  "dwave-neal, qbsolv"
Error " Could not find a version that satisfies the requirement qbsolv (from versions: )
No matching distribution found for qbsolv".
I have tried both version of python3 and 2 could you please enlighten me a bit. 
Thanks in advance.

**Comment by bellert** [comment]
The README should have said `pip install dwave-qbsolv`. It has been fixed now.

**Comment by bellert** [comment]
I was able to install dwave-neal with `pip install dwave-neal`. If you are still having problems there, please open an issue on that project: https://github.com/dwavesystems/dwave_neal/issues/new

**Comment by Frrank1** [comment]
Yes, I had it fixed the day I added the issue after talking to yanbo. Thanks for the follow up.
